apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-167662294
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-167662294
    app.kubernetes.io/part-of: test-app-167662294
  name: java-quarkus-167662294
  namespace: skhileri-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-167662294
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-167662294
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:24aa576a9533335efd25281a25910d78ea12c81e154f72d76b25f375fc63586d
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
