apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: test-app-167662294
    appstudio.openshift.io/component: java-quarkus-167662294
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: java-quarkus-167662294
  namespace: skhileri-tenant
spec:
  url: https://github.com/hac-test/devfile-sample-code-with-quarkus
